name: Publish Package to npmjs.com
on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
jobs:
  build-and-publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          registry-url: https://registry.npmjs.org/
          scope: "@intentui"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
